language: scala
before_install:
  - git clone git@github.com:Spacelift/amqp-scala-client.git ~/builds/amqp-scala-client
  - pushd ~/builds/amqp-scala-client
  - sbt publish-local
  - popd
script: sbt test
scala:
  - 2.12.1
jdk:
  - oraclejdk8
services:
  - rabbitmq
